
module.exports.result = ((param) => {
    // other complex calc1...
    // other complex calc2...
    // other complex calc3...
    return param.filter(each => each % 2 == 0);
})([1, 2, 3, 5, 7, 8, 13]);